# GoLic configuration for this repo.
# golic v0.3.0's embedded rules cover .js/.go/etc. but NOT the TypeScript/ESM
# source extensions this project ships. mergeRules keeps the embedded rules and
# adds C-style comment rules for .ts/.tsx/.mts/.mjs/.cjs so `task license`
# actually injects and verifies the Apache 2.0 header on every source file.
golic:
  # golic's apache2 header with the CNCF copyright line (cncf/foundation
  # copyright-notices.md): no year and no single holder, so this template
  # ignores `-c`.
  licenses:
    apache2-cncf: |
      Apache License 2.0

      Copyright The CryptOS Authors.

      Licensed under the Apache License, Version 2.0 (the "License");
      you may not use this file except in compliance with the License.
      You may obtain a copy of the License at

          http://www.apache.org/licenses/LICENSE-2.0

      Unless required by applicable law or agreed to in writing, software
      distributed under the License is distributed on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
      See the License for the specific language governing permissions and
      limitations under the License.
  mergeRules: true
  rules:
    .ts:
      prefix: /*
      suffix: "*/"
      under: []
    .tsx:
      prefix: /*
      suffix: "*/"
      under: []
    .mts:
      prefix: /*
      suffix: "*/"
      under: []
    .mjs:
      prefix: /*
      suffix: "*/"
      under: []
    .cjs:
      prefix: /*
      suffix: "*/"
      under: []
