// Generates src/icons/<Name>.tsx and src/icons/index.ts from assets/icons/*.svg.
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const header =
  readFileSync(new URL("../src/lib/cn.ts", import.meta.url), "utf8").split("*/", 1)[0] + "*/\n\n";
const srcDir = new URL("../assets/icons/", import.meta.url).pathname;
const outDir = new URL("../src/icons/", import.meta.url).pathname;
mkdirSync(outDir, { recursive: true });
const pascal = (n) => n.charAt(0).toUpperCase() + n.slice(1);
const exports = [];
for (const file of readdirSync(srcDir)
  .filter((f) => f.endsWith(".svg"))
  .toSorted()) {
  const raw = readFileSync(path.join(srcDir, file), "utf8");
  if (/c2pa|<metadata/i.test(raw)) throw new Error(`${file}: strip metadata first`);
  const inner = raw
    .replace(/^[\s\S]*?<svg[^>]*>/, "")
    .replace(/<\/svg>\s*$/, "")
    .replaceAll("stroke-width", "strokeWidth")
    .replaceAll("stroke-linecap", "strokeLinecap")
    .replaceAll("stroke-linejoin", "strokeLinejoin")
    .replaceAll("fill-rule", "fillRule")
    .replaceAll("clip-rule", "clipRule");
  const name = `Icon${pascal(file.replace(/\.svg$/, ""))}`;
  writeFileSync(
    path.join(outDir, `${name}.tsx`),
    `${header}// Generated by scripts/gen-icons.mjs. Do not edit.
import { type IconProps, IconBase } from "./icon-base";

export const ${name} = (props: IconProps) => (
  <IconBase {...props}>${inner}</IconBase>
);
`,
  );
  exports.push(`export { ${name} } from "./${name}";`);
}
writeFileSync(
  path.join(outDir, "index.ts"),
  `${header}// Generated by scripts/gen-icons.mjs. Do not edit.
export { type IconComponent, type IconProps } from "./icon-base";
${exports.join("\n")}
`,
);
