/*
Copyright The CryptOS Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Generated by scripts/gen-icons.mjs. Do not edit.
import { type IconProps, IconBase } from "./icon-base";

export const IconSun = (props: IconProps) => (
  <IconBase {...props}><circle cx="12" cy="12" r="4" fill="none"></circle><path d="M12 2v2" fill="none"></path><path d="M12 20v2" fill="none"></path><path d="M2 12h2" fill="none"></path><path d="M20 12h2" fill="none"></path><path d="M4.9 4.9l1.4 1.4" fill="none"></path><path d="M17.7 17.7l1.4 1.4" fill="none"></path><path d="M4.9 19.1l1.4-1.4" fill="none"></path><path d="M17.7 6.3l1.4-1.4" fill="none"></path></IconBase>
);
