/*
Copyright The CryptOS Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Generated by scripts/gen-icons.mjs. Do not edit.
import { type IconProps, IconBase } from "./icon-base";

export const IconFingerprint = (props: IconProps) => (
  <IconBase {...props}><path d="M5 4h4" fill="none"></path><path d="M11 4h3" fill="none"></path><path d="M16 4h3" fill="none"></path><path d="M5 9h2" fill="none"></path><path d="M9 9h5" fill="none"></path><path d="M16 9h3" fill="none"></path><path d="M5 14h6" fill="none"></path><path d="M13 14h2" fill="none"></path><path d="M17 14h2" fill="none"></path><path d="M5 19h3" fill="none"></path><path d="M10 19h4" fill="none"></path><path d="M16 19h3" fill="none"></path></IconBase>
);
